/**
 * Hardcoded e-commerce events for Phase 1.
 * Will be replaced by Sanity-backed data once the scraper is built.
 *
 * Scraper schedule: WEEKLY (Monday 06:00 UTC)
 *   - Events don't change daily — weekly is sufficient to catch
 *     new announcements, date shifts, and price changes.
 *
 * Sources to scrape in Phase 2:
 *   1.  online.marketing/ecommerce          — 40+ events calendar
 *   2.  eventible.com/e-commerce             — aggregator with reviews
 *   3.  ecommerceexpo.co.uk                  — UK flagship expo
 *   4.  digitalmarketing-conference.com      — DMWF series
 *   5.  aws.amazon.com/events                — AWS / Amazon events
 *   6.  10times.com/ecommerce                — global event directory
 *   7.  conferenceindex.org/conferences/ecommerce
 *   8.  startup.club/best-ecommerce-conferences
 *   9.  convertcart.com/blog/must-attend-top-ecommerce-conferences
 *  10.  absoluteweb.com/best-ecommerce-conferences
 *  11.  theretailexec.com/career/ecommerce-conferences
 *  12.  bigcommerce.com/blog/top-ecommerce-conferences
 *  13.  community.commercenext.com/top-ecommerce-conferences
 *  14.  elogic.co/blog/global-ecommerce-conferences
 *  15.  beanstalkevents.com                  — Beanstalk Conference
 *  16.  shoptalk.com                         — Shoptalk Spring + Europe
 *  17.  nrfbigshow.nrf.com                   — NRF Big Show
 *  18.  prospershow.com                      — Prosper Show
 *  19.  etailwest.wbresearch.com             — eTail series (West, Asia, Europe)
 *  20.  sellersummit.com                     — Seller Summit
 */

export const EVENTS_DATA = [
  // ──────────── NORTH AMERICA ────────────
  {
    _id: 'evt-001',
    name: 'Shoptalk Spring',
    startDate: '2026-03-22',
    endDate: '2026-03-25',
    location: 'Las Vegas, NV',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$2,650',
    description: 'The largest retail and e-commerce conference in the US, bringing together 10,000+ attendees from leading brands, retailers, and tech companies. Covers AI, social commerce, marketplaces, and supply chain innovation.',
    websiteUrl: 'https://shoptalk.com',
    tags: ['retail', 'DTC', 'AI', 'marketplaces'],
  },
  {
    _id: 'evt-002',
    name: 'NRF Big Show',
    startDate: '2026-01-11',
    endDate: '2026-01-13',
    location: 'New York, NY',
    country: 'US',
    region: 'North America',
    type: 'Expo',
    cost: '$1,200',
    description: 'The National Retail Federation\'s flagship event and the world\'s largest retail conference. 40,000+ attendees, 1,000+ exhibitors covering retail tech, omnichannel, and consumer trends.',
    websiteUrl: 'https://nrfbigshow.nrf.com',
    tags: ['retail', 'omnichannel', 'tech'],
  },
  {
    _id: 'evt-003',
    name: 'eTail West',
    startDate: '2026-02-23',
    endDate: '2026-02-26',
    location: 'Palm Springs, CA',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: '$3,499',
    description: 'Invite-only summit for senior e-commerce executives. Focused on growth strategies, personalization, and customer acquisition. Features 1:1 meetings and small-group workshops.',
    websiteUrl: 'https://etailwest.wbresearch.com',
    tags: ['DTC', 'growth', 'personalization'],
  },
  {
    _id: 'evt-004',
    name: 'Prosper Show',
    startDate: '2026-03-09',
    endDate: '2026-03-11',
    location: 'Las Vegas, NV',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$999',
    description: 'The largest conference for Amazon sellers. Deep-dive sessions on FBA optimization, advertising strategies, brand protection, and scaling marketplace businesses.',
    websiteUrl: 'https://prospershow.com',
    tags: ['Amazon', 'marketplaces', 'FBA', 'sellers'],
  },
  {
    _id: 'evt-008',
    name: 'Beanstalk Summit',
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    location: 'Brooklyn, NY',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: 'Invite only',
    description: 'Invite-only summit for DTC founders and brand operators. Practical sessions on scaling, retention strategies, and navigating rising ad costs. Known for high-quality networking.',
    websiteUrl: 'https://www.beanstalkevents.com',
    tags: ['e-commerce', 'DTC', 'founders', 'retention'],
  },
  {
    _id: 'evt-009',
    name: 'CommerceNext',
    startDate: '2026-06-23',
    endDate: '2026-06-25',
    location: 'New York, NY',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: '$1,995',
    description: 'Growth-focused summit for e-commerce and marketing leaders. Case studies from top brands on customer acquisition, loyalty, and data-driven merchandising.',
    websiteUrl: 'https://commercenext.com',
    tags: ['growth', 'loyalty', 'data', 'merchandising'],
  },
  {
    _id: 'evt-010',
    name: 'Seller Summit',
    startDate: '2026-05-05',
    endDate: '2026-05-07',
    location: 'Fort Lauderdale, FL',
    country: 'US',
    region: 'North America',
    type: 'Workshop',
    cost: '$1,297',
    description: 'Intensive workshop-style event for 7- and 8-figure e-commerce sellers. Hands-on sessions covering email marketing, conversion optimization, and multi-channel selling.',
    websiteUrl: 'https://sellersummit.com',
    tags: ['sellers', 'email marketing', 'conversion', 'multi-channel'],
  },
  {
    _id: 'evt-014',
    name: 'Amazon Accelerate',
    startDate: '2026-09-14',
    endDate: '2026-09-15',
    location: 'Seattle, WA',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$449',
    description: 'Amazon\'s annual seller conference. Product roadmap reveals, hands-on workshops for advertising and fulfillment, and direct access to Amazon category managers.',
    websiteUrl: 'https://accelerate.amazon.com',
    tags: ['Amazon', 'sellers', 'advertising', 'FBA'],
  },
  {
    _id: 'evt-019',
    name: 'Retail Innovation Conference',
    startDate: '2026-06-09',
    endDate: '2026-06-11',
    location: 'Chicago, IL',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$1,599',
    description: 'Focused on emerging retail technologies — unified commerce, AI-powered merchandising, and in-store digital experiences. 2,000+ retail innovators attend annually.',
    websiteUrl: 'https://retailinnovationconference.com',
    tags: ['retail tech', 'unified commerce', 'AI', 'in-store'],
  },
  {
    _id: 'evt-020',
    name: 'AWS re:Invent',
    startDate: '2026-11-30',
    endDate: '2026-12-04',
    location: 'Las Vegas, NV',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$2,099',
    description: 'Amazon Web Services\' flagship cloud conference. Features dedicated e-commerce and retail tracks covering serverless storefronts, ML-powered recommendations, and cloud-native commerce architectures.',
    websiteUrl: 'https://aws.amazon.com/events',
    tags: ['AWS', 'cloud', 'infrastructure', 'AI/ML'],
  },
  {
    _id: 'evt-027',
    name: 'IRCE (Internet Retailer)',
    startDate: '2026-06-16',
    endDate: '2026-06-18',
    location: 'Chicago, IL',
    country: 'US',
    region: 'North America',
    type: 'Expo',
    cost: 'Free (expo)',
    description: 'One of the longest-running e-commerce tradeshows. 10,000+ attendees explore 600+ exhibitors showcasing platforms, fulfillment tech, payment solutions, and marketing tools.',
    websiteUrl: 'https://www.irce.com',
    tags: ['e-commerce', 'platforms', 'fulfillment', 'payments'],
  },
  {
    _id: 'evt-030',
    name: 'SubSummit',
    startDate: '2026-05-19',
    endDate: '2026-05-21',
    location: 'Dallas, TX',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: '$1,495',
    description: 'The world\'s largest conference dedicated to subscription commerce. Covers retention, churn reduction, subscription box logistics, and recurring revenue strategies for DTC brands.',
    websiteUrl: 'https://www.subsummit.com',
    tags: ['subscriptions', 'retention', 'DTC', 'recurring revenue'],
  },
  {
    _id: 'evt-033',
    name: 'ShopTalk Fall (Meetup)',
    startDate: '2026-10-26',
    endDate: '2026-10-28',
    location: 'Chicago, IL',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: 'Free',
    description: 'Shoptalk\'s invite-only fall gathering for senior retail executives. Intimate format with curated double-opt-in meetings and roundtable discussions on 2027 commerce strategies.',
    websiteUrl: 'https://shoptalk.com/meetup',
    tags: ['retail', 'networking', 'strategy', 'executive'],
  },

  // ──────────── EUROPE ────────────
  {
    _id: 'evt-005',
    name: 'Shoptalk Europe',
    startDate: '2026-06-09',
    endDate: '2026-06-11',
    location: 'Barcelona, Spain',
    country: 'ES',
    region: 'Europe',
    type: 'Conference',
    cost: '\u20AC1,800',
    description: 'European edition of Shoptalk, bringing together 3,000+ retailers, brands, and tech leaders. Covers cross-border commerce, sustainability in retail, and European market dynamics.',
    websiteUrl: 'https://shoptalkeurope.com',
    tags: ['retail', 'cross-border', 'sustainability'],
  },
  {
    _id: 'evt-006',
    name: 'eCommerce Expo',
    startDate: '2026-09-23',
    endDate: '2026-09-24',
    location: 'London, UK',
    country: 'GB',
    region: 'Europe',
    type: 'Expo',
    cost: 'Free',
    description: 'The UK\'s leading e-commerce exhibition at ExCeL London. 12,000+ visitors, 300+ exhibitors showcasing platforms, payments, logistics, and marketing solutions.',
    websiteUrl: 'https://www.ecommerceexpo.co.uk',
    tags: ['platforms', 'payments', 'logistics'],
  },
  {
    _id: 'evt-007',
    name: 'DMWF Global',
    startDate: '2026-05-06',
    endDate: '2026-05-07',
    location: 'London, UK',
    country: 'GB',
    region: 'Europe',
    type: 'Conference',
    cost: '\u00A3899',
    description: 'Digital Marketing World Forum brings 3,000+ senior marketers. 10 specialized tracks covering AI-driven marketing, social commerce, and performance marketing strategies.',
    websiteUrl: 'https://www.digitalmarketing-conference.com',
    tags: ['digital marketing', 'social commerce', 'AI'],
  },
  {
    _id: 'evt-012',
    name: 'White Label World Expo',
    startDate: '2026-03-04',
    endDate: '2026-03-05',
    location: 'Frankfurt, Germany',
    country: 'DE',
    region: 'Europe',
    type: 'Expo',
    cost: 'Free',
    description: 'Europe\'s largest sourcing and white-label products expo. 10,000+ visitors discover new product lines, private-label manufacturers, and packaging innovations.',
    websiteUrl: 'https://www.whitelabelworldexpo.com',
    tags: ['sourcing', 'private label', 'manufacturing'],
  },
  {
    _id: 'evt-015',
    name: 'E-Show Barcelona',
    startDate: '2026-05-20',
    endDate: '2026-05-21',
    location: 'Barcelona, Spain',
    country: 'ES',
    region: 'Europe',
    type: 'Expo',
    cost: 'Free',
    description: 'Southern Europe\'s biggest e-commerce and digital marketing expo. 15,000+ attendees explore logistics tech, payment solutions, and marketplace strategies for the EU market.',
    websiteUrl: 'https://www.the-eshow.com',
    tags: ['logistics', 'payments', 'EU market'],
  },
  {
    _id: 'evt-016',
    name: 'K5 Conference',
    startDate: '2026-06-03',
    endDate: '2026-06-04',
    location: 'Berlin, Germany',
    country: 'DE',
    region: 'Europe',
    type: 'Conference',
    cost: '\u20AC1,290',
    description: 'Germany\'s leading e-commerce strategy conference. Curated for decision-makers with deep dives into platform economics, DACH market trends, and retail media.',
    websiteUrl: 'https://www.k5.de',
    tags: ['strategy', 'DACH', 'retail media', 'platforms'],
  },
  {
    _id: 'evt-021',
    name: 'DMWF Amsterdam',
    startDate: '2026-11-18',
    endDate: '2026-11-19',
    location: 'Amsterdam, Netherlands',
    country: 'NL',
    region: 'Europe',
    type: 'Conference',
    cost: '\u20AC799',
    description: 'The Netherlands edition of Digital Marketing World Forum. Strong focus on privacy-first marketing, EU regulation compliance, and emerging martech across the Benelux and Nordic markets.',
    websiteUrl: 'https://www.digitalmarketing-conference.com',
    tags: ['digital marketing', 'privacy', 'martech', 'GDPR'],
  },
  {
    _id: 'evt-022',
    name: 'Paris Retail Week',
    startDate: '2026-09-15',
    endDate: '2026-09-17',
    location: 'Paris, France',
    country: 'FR',
    region: 'Europe',
    type: 'Expo',
    cost: 'Free',
    description: 'France\'s premier retail and e-commerce trade show. 30,000+ professionals explore omnichannel retail, unified commerce solutions, and luxury e-commerce trends in the French market.',
    websiteUrl: 'https://www.parisretailweek.com',
    tags: ['retail', 'omnichannel', 'luxury', 'French market'],
  },
  {
    _id: 'evt-028',
    name: 'eTail Europe',
    startDate: '2026-06-22',
    endDate: '2026-06-24',
    location: 'London, UK',
    country: 'GB',
    region: 'Europe',
    type: 'Summit',
    cost: '\u00A32,200',
    description: 'Europe\'s leading invite-only e-commerce summit for senior leaders. Features pre-scheduled 1:1 meetings, interactive roundtables, and case studies from Europe\'s top online retailers.',
    websiteUrl: 'https://etaileurope.wbresearch.com',
    tags: ['e-commerce', 'executive', 'networking', 'strategy'],
  },

  // ──────────── ASIA-PACIFIC ────────────
  {
    _id: 'evt-011',
    name: 'eTail Asia',
    startDate: '2026-11-10',
    endDate: '2026-11-12',
    location: 'Singapore',
    country: 'SG',
    region: 'Asia-Pacific',
    type: 'Summit',
    cost: '$2,200',
    description: 'Southeast Asia\'s premier e-commerce summit. Covers mobile commerce, super-app ecosystems, and the fast-growing APAC digital economy. 800+ senior retail leaders.',
    websiteUrl: 'https://etailasia.wbresearch.com',
    tags: ['mobile commerce', 'APAC', 'super-apps'],
  },
  {
    _id: 'evt-017',
    name: 'Delivered Asia',
    startDate: '2026-08-19',
    endDate: '2026-08-20',
    location: 'Sydney, Australia',
    country: 'AU',
    region: 'Asia-Pacific',
    type: 'Conference',
    cost: 'A$995',
    description: 'Australia\'s top e-commerce and logistics conference. Covers last-mile innovation, returns management, and cross-border fulfillment across the Asia-Pacific region.',
    websiteUrl: 'https://deliveredconference.com',
    tags: ['logistics', 'last-mile', 'cross-border', 'fulfillment'],
  },
  {
    _id: 'evt-023',
    name: 'Alibaba Gateway Summit',
    startDate: '2026-09-09',
    endDate: '2026-09-10',
    location: 'Hangzhou, China',
    country: 'CN',
    region: 'Asia-Pacific',
    type: 'Summit',
    cost: 'Free',
    description: 'Alibaba\'s annual global sellers summit. Keynotes on cross-border trade through AliExpress and Tmall Global, AI-powered sourcing tools, and the future of B2B marketplace commerce.',
    websiteUrl: 'https://www.alibaba.com',
    tags: ['Alibaba', 'cross-border', 'B2B', 'marketplaces'],
  },
  {
    _id: 'evt-029',
    name: 'Japan IT Week (E-Commerce)',
    startDate: '2026-10-28',
    endDate: '2026-10-30',
    location: 'Tokyo, Japan',
    country: 'JP',
    region: 'Asia-Pacific',
    type: 'Expo',
    cost: 'Free',
    description: 'Japan\'s largest IT trade show includes a dedicated e-commerce zone. 1,500+ exhibitors covering online payment systems, logistics automation, and the Japanese marketplace ecosystem.',
    websiteUrl: 'https://www.japan-it-autumn.jp/en-gb.html',
    tags: ['Japan', 'payments', 'logistics', 'marketplaces'],
  },

  // ──────────── LATIN AMERICA ────────────
  {
    _id: 'evt-024',
    name: 'eCommerce Day Santiago',
    startDate: '2026-07-08',
    endDate: '2026-07-09',
    location: 'Santiago, Chile',
    country: 'CL',
    region: 'Latin America',
    type: 'Conference',
    cost: 'Free',
    description: 'Part of the eCommerce Day series across Latin America. Covers the rapidly growing Chilean and South American e-commerce market, local payment methods, and last-mile challenges in the region.',
    websiteUrl: 'https://www.ecommerceday.org',
    tags: ['LATAM', 'payments', 'last-mile', 'growth markets'],
  },
  {
    _id: 'evt-025',
    name: 'VTEX DAY',
    startDate: '2026-06-02',
    endDate: '2026-06-03',
    location: 'S\u00E3o Paulo, Brazil',
    country: 'BR',
    region: 'Latin America',
    type: 'Conference',
    cost: 'R$890',
    description: 'Latin America\'s largest digital commerce event hosted by VTEX. 20,000+ attendees from across the region explore composable commerce, marketplace strategies, and the booming Brazilian e-commerce ecosystem.',
    websiteUrl: 'https://vtexday.vtex.com',
    tags: ['LATAM', 'composable commerce', 'marketplaces', 'Brazil'],
  },
  {
    _id: 'evt-031',
    name: 'eCommerce Day Buenos Aires',
    startDate: '2026-08-12',
    endDate: '2026-08-13',
    location: 'Buenos Aires, Argentina',
    country: 'AR',
    region: 'Latin America',
    type: 'Conference',
    cost: 'Free',
    description: 'Argentina\'s premier e-commerce conference bringing together brands, retailers, and logistics providers. Covers MercadoLibre ecosystem strategies, cross-border LATAM trade, and fintech-driven commerce.',
    websiteUrl: 'https://www.ecommerceday.org',
    tags: ['LATAM', 'MercadoLibre', 'fintech', 'Argentina'],
  },

  // ──────────── MIDDLE EAST & AFRICA ────────────
  {
    _id: 'evt-026',
    name: 'Seamless Middle East',
    startDate: '2026-05-26',
    endDate: '2026-05-27',
    location: 'Dubai, UAE',
    country: 'AE',
    region: 'Middle East & Africa',
    type: 'Expo',
    cost: 'Free',
    description: 'The Middle East\'s largest fintech, e-commerce, and retail exhibition. 15,000+ attendees explore payment innovation, last-mile logistics in the Gulf region, and the rapidly growing MENA digital economy.',
    websiteUrl: 'https://www.terrapinn.com/exhibition/seamless-middle-east',
    tags: ['MENA', 'fintech', 'payments', 'logistics'],
  },
  {
    _id: 'evt-032',
    name: 'Africa eCommerce Summit',
    startDate: '2026-10-14',
    endDate: '2026-10-15',
    location: 'Nairobi, Kenya',
    country: 'KE',
    region: 'Middle East & Africa',
    type: 'Summit',
    cost: '$350',
    description: 'East Africa\'s growing e-commerce summit covering mobile money integration, Jumia and Takealot marketplace strategies, and last-mile delivery innovation across the African continent.',
    websiteUrl: 'https://www.africaecommercesummit.com',
    tags: ['Africa', 'mobile money', 'marketplaces', 'last-mile'],
  },

  // ──────────── GLOBAL / VIRTUAL ────────────
  {
    _id: 'evt-013',
    name: 'Shopify Editions',
    startDate: '2026-07-15',
    endDate: '2026-07-15',
    location: 'Virtual',
    country: 'Global',
    region: 'Global/Virtual',
    type: 'Webinar',
    cost: 'Free',
    description: 'Shopify\'s biannual product reveal showcasing 100+ new features, APIs, and platform updates. Essential viewing for Shopify merchants, developers, and app partners.',
    websiteUrl: 'https://www.shopify.com/editions',
    tags: ['Shopify', 'platforms', 'product launches'],
  },
  {
    _id: 'evt-018',
    name: 'Global E-Commerce Summit',
    startDate: '2026-10-07',
    endDate: '2026-10-08',
    location: 'Virtual',
    country: 'Global',
    region: 'Global/Virtual',
    type: 'Webinar',
    cost: 'Free',
    description: 'Virtual summit connecting e-commerce leaders across time zones. Panel discussions on global expansion strategies, localization, and emerging market opportunities.',
    websiteUrl: 'https://globalecommercesummit.com',
    tags: ['global expansion', 'localization', 'emerging markets'],
  },
  {
    _id: 'evt-034',
    name: 'AWS Commerce Webinar Series',
    startDate: '2026-04-22',
    endDate: '2026-04-22',
    location: 'Virtual',
    country: 'Global',
    region: 'Global/Virtual',
    type: 'Webinar',
    cost: 'Free',
    description: 'Monthly AWS webinar focused on commerce workloads. Covers headless architecture patterns, real-time personalization with Amazon Personalize, and serverless checkout flows on AWS.',
    websiteUrl: 'https://aws.amazon.com/events',
    tags: ['AWS', 'headless', 'personalization', 'serverless'],
  },

  // ──────────── 2027 EVENTS ────────────
  {
    _id: 'evt-035',
    name: 'NRF Big Show 2027',
    startDate: '2027-01-10',
    endDate: '2027-01-12',
    location: 'New York, NY',
    country: 'US',
    region: 'North America',
    type: 'Expo',
    cost: '$1,300',
    description: 'The 2027 edition of the world\'s largest retail conference. 40,000+ attendees expected with expanded AI, autonomous retail, and composable commerce tracks.',
    websiteUrl: 'https://nrfbigshow.nrf.com',
    tags: ['retail', 'omnichannel', 'AI', 'composable commerce'],
  },
  {
    _id: 'evt-036',
    name: 'eTail West 2027',
    startDate: '2027-02-22',
    endDate: '2027-02-25',
    location: 'Palm Springs, CA',
    country: 'US',
    region: 'North America',
    type: 'Summit',
    cost: '$3,699',
    description: 'The 2027 edition of the invite-only e-commerce executive summit. New tracks on AI-native commerce, retail media networks, and post-cookie customer acquisition.',
    websiteUrl: 'https://etailwest.wbresearch.com',
    tags: ['executive', 'AI', 'retail media', 'customer acquisition'],
  },
  {
    _id: 'evt-037',
    name: 'Prosper Show 2027',
    startDate: '2027-03-08',
    endDate: '2027-03-10',
    location: 'Las Vegas, NV',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$1,099',
    description: 'Amazon seller conference returns with expanded coverage of Amazon\'s AI tools, Supply Chain by Amazon, and emerging marketplace strategies for 2027.',
    websiteUrl: 'https://prospershow.com',
    tags: ['Amazon', 'sellers', 'AI tools', 'supply chain'],
  },
  {
    _id: 'evt-038',
    name: 'Shoptalk Spring 2027',
    startDate: '2027-03-21',
    endDate: '2027-03-24',
    location: 'Las Vegas, NV',
    country: 'US',
    region: 'North America',
    type: 'Conference',
    cost: '$2,800',
    description: 'The 2027 edition of retail\'s biggest conference. Expected themes include agentic commerce, autonomous supply chains, and the convergence of social and retail media.',
    websiteUrl: 'https://shoptalk.com',
    tags: ['retail', 'agentic commerce', 'social commerce', 'retail media'],
  },
  {
    _id: 'evt-039',
    name: 'White Label World Expo 2027',
    startDate: '2027-03-03',
    endDate: '2027-03-04',
    location: 'Frankfurt, Germany',
    country: 'DE',
    region: 'Europe',
    type: 'Expo',
    cost: 'Free',
    description: 'The 2027 edition of Europe\'s largest sourcing expo. New focus areas include sustainable packaging mandates, nearshoring trends, and AI-powered product development.',
    websiteUrl: 'https://www.whitelabelworldexpo.com',
    tags: ['sourcing', 'sustainability', 'nearshoring', 'private label'],
  },
  {
    _id: 'evt-040',
    name: 'DMWF Global 2027',
    startDate: '2027-05-05',
    endDate: '2027-05-06',
    location: 'London, UK',
    country: 'GB',
    region: 'Europe',
    type: 'Conference',
    cost: '\u00A3949',
    description: 'Digital Marketing World Forum 2027 with expanded commerce tracks. New sessions on AI content generation at scale, privacy-first attribution, and the cookieless advertising landscape.',
    websiteUrl: 'https://www.digitalmarketing-conference.com',
    tags: ['digital marketing', 'AI content', 'privacy', 'attribution'],
  },
  {
    _id: 'evt-041',
    name: 'DMWF Singapore 2027',
    startDate: '2027-02-10',
    endDate: '2027-02-11',
    location: 'Singapore',
    country: 'SG',
    region: 'Asia-Pacific',
    type: 'Conference',
    cost: '$750',
    description: 'The APAC edition of Digital Marketing World Forum. Covers Southeast Asian social commerce, live-stream selling trends, and super-app marketing strategies.',
    websiteUrl: 'https://www.digitalmarketing-conference.com',
    tags: ['APAC', 'social commerce', 'live-stream', 'super-apps'],
  },
  {
    _id: 'evt-042',
    name: 'eCommerce Day Mexico City',
    startDate: '2027-03-18',
    endDate: '2027-03-19',
    location: 'Mexico City, Mexico',
    country: 'MX',
    region: 'Latin America',
    type: 'Conference',
    cost: 'Free',
    description: 'Part of the eCommerce Day LATAM series. Covers the booming Mexican e-commerce market, Amazon Mexico strategies, and cross-border trade between the US and Latin America.',
    websiteUrl: 'https://www.ecommerceday.org',
    tags: ['LATAM', 'Mexico', 'Amazon', 'cross-border'],
  },
  {
    _id: 'evt-043',
    name: 'Seamless Saudi Arabia',
    startDate: '2027-02-24',
    endDate: '2027-02-25',
    location: 'Riyadh, Saudi Arabia',
    country: 'SA',
    region: 'Middle East & Africa',
    type: 'Expo',
    cost: 'Free',
    description: 'Saudi Arabia\'s largest fintech and e-commerce expo. Covers Vision 2030 digital commerce initiatives, the fast-growing Saudi online retail market, and regional payment innovation.',
    websiteUrl: 'https://www.terrapinn.com/exhibition/seamless-saudi-arabia',
    tags: ['MENA', 'Saudi Arabia', 'fintech', 'Vision 2030'],
  },
];
