// DC Index basket — public e-commerce + commerce-adjacent names.
// Grouped into 3 sub-indexes: Brands, Marketplaces, Software.
// Cap any single name at 15% after rebalancing.

export const DC_INDEX_BASKET = [
  // ── Brands (41) ──
  { symbol: 'NKE',  name: 'Nike',               bucket: 'Brands' },
  { symbol: 'TPR',  name: 'Tapestry',            bucket: 'Brands' },
  { symbol: 'RL',   name: 'Ralph Lauren',        bucket: 'Brands' },
  { symbol: 'LULU', name: 'Lululemon',           bucket: 'Brands' },
  { symbol: 'DECK', name: 'Deckers Outdoor',     bucket: 'Brands' },
  { symbol: 'ONON', name: 'On Holding',          bucket: 'Brands' },
  { symbol: 'CHWY', name: 'Chewy',              bucket: 'Brands' },
  { symbol: 'CELH', name: 'Celsius',             bucket: 'Brands' },
  { symbol: 'BROS', name: 'Dutch Bros',          bucket: 'Brands' },
  { symbol: 'BIRK', name: 'Birkenstock',         bucket: 'Brands' },
  { symbol: 'CROX', name: 'Crocs',              bucket: 'Brands' },
  { symbol: 'ANF',  name: 'Abercrombie & Fitch', bucket: 'Brands' },
  { symbol: 'HIMS', name: 'Hims & Hers',        bucket: 'Brands' },
  { symbol: 'ELF',  name: 'e.l.f. Beauty',      bucket: 'Brands' },
  { symbol: 'PVH',  name: 'PVH Corp.',          bucket: 'Brands' },
  { symbol: 'BBWI', name: 'Bath & Body Works',  bucket: 'Brands' },
  { symbol: 'VSCO', name: "Victoria's Secret",   bucket: 'Brands' },
  { symbol: 'KTB',  name: 'Kontoor Brands',     bucket: 'Brands' },
  { symbol: 'FRPT', name: 'Freshpet',           bucket: 'Brands' },
  { symbol: 'YETI', name: 'YETI',               bucket: 'Brands' },
  { symbol: 'COLM', name: 'Columbia Sportswear', bucket: 'Brands' },
  { symbol: 'COCO', name: 'Vita Coco',          bucket: 'Brands' },
  { symbol: 'WRBY', name: 'Warby Parker',       bucket: 'Brands' },
  { symbol: 'UAA',  name: 'Under Armour',       bucket: 'Brands' },
  { symbol: 'CPRI', name: 'Capri Holdings',     bucket: 'Brands' },
  { symbol: 'SHOO', name: 'Steve Madden',       bucket: 'Brands' },
  { symbol: 'FIGS', name: 'FIGS',               bucket: 'Brands' },
  { symbol: 'PTON', name: 'Peloton',            bucket: 'Brands' },
  { symbol: 'SONO', name: 'Sonos',              bucket: 'Brands' },
  { symbol: 'RVLV', name: 'Revolve',            bucket: 'Brands' },
  { symbol: 'OLPX', name: 'Olaplex',            bucket: 'Brands' },
  { symbol: 'WWW',  name: 'Wolverine World Wide', bucket: 'Brands' },
  { symbol: 'GIII', name: 'G-III Apparel',      bucket: 'Brands' },
  { symbol: 'CRI',  name: "Carter's",            bucket: 'Brands' },
  { symbol: 'GOOS', name: 'Canada Goose',       bucket: 'Brands' },
  { symbol: 'ODD',  name: 'Oddity Tech',        bucket: 'Brands' },
  { symbol: 'SFIX', name: 'Stitch Fix',         bucket: 'Brands' },
  { symbol: 'HNST', name: 'Honest Company',     bucket: 'Brands' },
  { symbol: 'XPOF', name: 'Xponential Fitness', bucket: 'Brands' },
  { symbol: 'LOVE', name: 'Lovesac',            bucket: 'Brands' },
  { symbol: 'RENT', name: 'Rent the Runway',    bucket: 'Brands' },
  { symbol: 'BIRD', name: 'Allbirds',           bucket: 'Brands' },

  // ── Marketplaces (24) ──
  { symbol: 'AMZN', name: 'Amazon',             bucket: 'Marketplaces' },
  { symbol: 'BABA', name: 'Alibaba',            bucket: 'Marketplaces' },
  { symbol: 'SHOP', name: 'Shopify',            bucket: 'Marketplaces' },
  { symbol: 'PDD',  name: 'PDD (Temu)',         bucket: 'Marketplaces' },
  { symbol: 'BKNG', name: 'Booking Holdings',   bucket: 'Marketplaces' },
  { symbol: 'MELI', name: 'MercadoLibre',       bucket: 'Marketplaces' },
  { symbol: 'DASH', name: 'DoorDash',           bucket: 'Marketplaces' },
  { symbol: 'CVNA', name: 'Carvana',            bucket: 'Marketplaces' },
  { symbol: 'SE',   name: 'Sea Limited',        bucket: 'Marketplaces' },
  { symbol: 'EBAY', name: 'eBay',               bucket: 'Marketplaces' },
  { symbol: 'JD',   name: 'JD.com',             bucket: 'Marketplaces' },
  { symbol: 'CPNG', name: 'Coupang',            bucket: 'Marketplaces' },
  { symbol: 'GRAB', name: 'Grab Holdings',      bucket: 'Marketplaces' },
  { symbol: 'RKUNY', name: 'Rakuten',           bucket: 'Marketplaces' },
  { symbol: 'CART', name: 'Instacart',          bucket: 'Marketplaces' },
  { symbol: 'W',    name: 'Wayfair',            bucket: 'Marketplaces' },
  { symbol: 'VIPS', name: 'Vipshop',            bucket: 'Marketplaces' },
  { symbol: 'ZAL',  name: 'Zalando',            bucket: 'Marketplaces' },
  { symbol: 'ETSY', name: 'Etsy',               bucket: 'Marketplaces' },
  { symbol: 'MCARY', name: 'Mercari',           bucket: 'Marketplaces' },
  { symbol: 'REAL', name: 'The RealReal',       bucket: 'Marketplaces' },
  { symbol: 'JMIA', name: 'Jumia',              bucket: 'Marketplaces' },
  { symbol: 'TDUP', name: 'ThredUp',            bucket: 'Marketplaces' },
  { symbol: 'DIBS', name: '1stDibs',            bucket: 'Marketplaces' },

  // ── Software (50) ──
  { symbol: 'V',    name: 'Visa',               bucket: 'Software' },
  { symbol: 'MA',   name: 'Mastercard',         bucket: 'Software' },
  { symbol: 'ADBE', name: 'Adobe',              bucket: 'Software' },
  { symbol: 'UPS',  name: 'UPS',                bucket: 'Software' },
  { symbol: 'FDX',  name: 'FedEx',              bucket: 'Software' },
  { symbol: 'NET',  name: 'Cloudflare',         bucket: 'Software' },
  { symbol: 'PYPL', name: 'PayPal',             bucket: 'Software' },
  { symbol: 'XYZ',  name: 'Block',              bucket: 'Software' },
  { symbol: 'DDOG', name: 'Datadog',            bucket: 'Software' },
  { symbol: 'ADYEN', name: 'Adyen',             bucket: 'Software' },
  { symbol: 'FISV', name: 'Fiserv',             bucket: 'Software' },
  { symbol: 'FIS',  name: 'FIS',                bucket: 'Software' },
  { symbol: 'XPO',  name: 'XPO Logistics',      bucket: 'Software' },
  { symbol: 'AFRM', name: 'Affirm',             bucket: 'Software' },
  { symbol: 'TWLO', name: 'Twilio',             bucket: 'Software' },
  { symbol: 'GPN',  name: 'Global Payments',    bucket: 'Software' },
  { symbol: 'TOST', name: 'Toast',              bucket: 'Software' },
  { symbol: 'AKAM', name: 'Akamai',             bucket: 'Software' },
  { symbol: 'PINS', name: 'Pinterest',          bucket: 'Software' },
  { symbol: 'HUBS', name: 'HubSpot',            bucket: 'Software' },
  { symbol: 'GDDY', name: 'GoDaddy',            bucket: 'Software' },
  { symbol: 'TTD',  name: 'The Trade Desk',     bucket: 'Software' },
  { symbol: 'SNAP', name: 'Snap',               bucket: 'Software' },
  { symbol: 'MANH', name: 'Manhattan Assoc.',    bucket: 'Software' },
  { symbol: 'GXO',  name: 'GXO Logistics',      bucket: 'Software' },
  { symbol: 'DSGX', name: 'Descartes Systems',  bucket: 'Software' },
  { symbol: 'GLBE', name: 'Global-e',           bucket: 'Software' },
  { symbol: 'KLAR', name: 'Klarna',              bucket: 'Software' },
  { symbol: 'KVYO', name: 'Klaviyo',            bucket: 'Software' },
  { symbol: 'ESTC', name: 'Elastic',            bucket: 'Software' },
  { symbol: 'FOUR', name: 'Shift4 Payments',    bucket: 'Software' },
  { symbol: 'CMRC', name: 'Commerce.com',       bucket: 'Software' },
  { symbol: 'DLO',  name: 'dLocal',             bucket: 'Software' },
  { symbol: 'BILL', name: 'Bill Holdings',      bucket: 'Software' },
  { symbol: 'FSLY', name: 'Fastly',             bucket: 'Software' },
  { symbol: 'BRZE', name: 'Braze',              bucket: 'Software' },
  { symbol: 'SEZL', name: 'Sezzle',             bucket: 'Software' },
  { symbol: 'MQ',   name: 'Marqeta',            bucket: 'Software' },
  { symbol: 'PAYO', name: 'Payoneer',           bucket: 'Software' },
  { symbol: 'RAMP', name: 'LiveRamp',           bucket: 'Software' },
  { symbol: 'DV',   name: 'DoubleVerify',       bucket: 'Software' },
  { symbol: 'FLYW', name: 'Flywire',            bucket: 'Software' },
  { symbol: 'CXM',  name: 'Sprinklr',           bucket: 'Software' },
  { symbol: 'LSPD', name: 'Lightspeed',         bucket: 'Software' },
  { symbol: 'PGY',  name: 'Pagaya',             bucket: 'Software' },
  { symbol: 'TBLA', name: 'Taboola',            bucket: 'Software' },
  { symbol: 'CRTO', name: 'Criteo',             bucket: 'Software' },
  { symbol: 'AMPL', name: 'Amplitude',          bucket: 'Software' },
  { symbol: 'VTEX', name: 'VTEX',               bucket: 'Software' },
  { symbol: 'RSKD', name: 'Riskified',          bucket: 'Software' },
];

// The ticker bar on the homepage shows this trimmed set.
export const TICKER_SYMBOLS = ['AMZN', 'SHOP', 'ETSY', 'MELI', 'CVNA'];
